- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - notepadplusplus
  - putty
  - python
  - git
  - 7zip
  - sysinternals
  - wget
  - pstools

- name: Change the hostname to domain-controller
  win_hostname:
    name: domain-controller
  register: win_hostname

- name: Reboot
  win_reboot:
  when: win_hostname.reboot_required
  
- name: Ensure that Administrator is present with a valid password
  win_user:
    name: Administrator
    password: StrongPass123!
    password_never_expires: yes
    state: present
  ignore_errors: yes

- name: Ensure that cyberloop.local domain exixts
  win_domain:
    dns_domain_name: cyberloop.local
    safe_mode_password: StrongPass123!
  register: check_domain

- name: Reboot to complete cyberloop.local domain creation
  win_reboot:
  when: check_domain.changed

- name: Ensure the server is a domain controller
  win_domain_controller:
    dns_domain_name: cyberloop.local
    domain_admin_user: Administrator@cyberloop.local
    domain_admin_password: StrongPass123!
    safe_mode_password: StrongPass123!
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
  register: check_domain_controller

- name: Reboot to complete domain controller setup
  win_reboot:
  when: check_domain_controller.changed

- name: Check for xDnsServer Powershell module
  win_psmodule:
    name: xDnsServer
    state: present

- name: Configure DNS Forwarders
  win_dsc:
    resource_name: xDnsServerSetting
    Name: DNSServerProperties
    NoRecursion: false
    Forwarders:
      - "8.8.8.8"
      - "8.8.4.4"

- name: Ensure that admin@cyberloop.local is present as Domain Admin
  win_domain_user:
    name: admin
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=CYBERLOOP,dc=local
    groups:
      - Domain Admins

- name: Ensure that bob@cyberloop.local is present in OU cn=Users,dc=CYBERLOOP,dc=local
  win_domain_user:
    name: bob
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=CYBERLOOP,dc=local
    groups:
      - Users

- name: Ensure that alice@cyberloop.local is present in OU cn=Users,dc=CYBERLOOP,dc=local
  win_domain_user:
    name: alice
    password: StrongPass123!
    password_never_expires: yes
    state: present
    path: cn=Users,dc=CYBERLOOP,dc=local
    groups:
      - Users

- name: Create AllTeams group
  win_domain_group:
    name: allTeams
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create DBAOracle
  win_domain_group:
    name: DBAOracle
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create DBASQLServer
  win_domain_group:
    name: DBASQLServer
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create DBAMongo group
  win_domain_group:
    name: DBAMongo
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create DBARedis group
  win_domain_group:
    name: DBARedis
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create DBAEnterprise Group ...
  win_domain_group:
    name: DBAEnterprise
    scope: global
    path: DC=cyberloop,DC=local
    state: present

- name: Create a Test Group ...
  win_domain_group:
    name: JustATestDemo
    scope: global
    path: DC=cyberloop,DC=local
    state: present
