USE [master]
GO

/****** Object:  Database [Clients]    Script Date: 19/10/2016 22:11:34 ******/
CREATE DATABASE [Clients]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Clients', FILENAME = N'C:\Userdbvol01\DatabaseFiles\Test\Clients.mdf' , SIZE = 16384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Clients_log', FILENAME = N'C:\Userdbvol01\DatabaseLogs\Test\Clients_log.ldf' , SIZE = 69760KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Clients] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clients].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Clients] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Clients] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Clients] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Clients] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Clients] SET ARITHABORT OFF 
GO

ALTER DATABASE [Clients] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Clients] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Clients] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Clients] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Clients] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Clients] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Clients] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Clients] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Clients] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Clients] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Clients] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Clients] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Clients] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Clients] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Clients] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Clients] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Clients] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Clients] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Clients] SET  MULTI_USER 
GO

ALTER DATABASE [Clients] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Clients] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Clients] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Clients] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Clients] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Clients] SET  READ_WRITE 
GO


